# Generated by Django 3.1.4 on 2020-12-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory_fk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
